name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - name: Build
        run: go run build/build.go

      - name: Sign
        uses: tristan-weil/ghaction-checksum-sign-artifact@v1.0.1
        with:
          path: dist/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.bz2
            dist/*.zip
            dist/SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
